import express from "express";
import { protect } from "../middlewares/authMiddleware1.js";
import WhatsAppSession from "../models/WhatsAppSession.js";

import {
  initWhatsAppUser,
  getClient,
  destroyClient,
} from "../services/whatsapp.manager.js";

const router = express.Router();

/**
 * POST /whatsapp/connect
 * Starts WhatsApp initialization (QR or session restore)
 */
router.post("/connect", protect, async (req, res) => {
  try {
    const userId = req.user?.id;
    if (!userId)
      return res.status(400).json({ message: "User ID missing" });

    // 🔑 Manager handles everything (QR, session, persistence)
    await initWhatsAppUser(userId);

    res.json({
      success: true,
      message: "WhatsApp initialization started",
    });
  } catch (err) {
    console.error("[WA ROUTES] /connect error:", err);
    res.status(500).json({
      message: "Failed to initialize WhatsApp",
      error: err.message,
    });
  }
});

/**
 * GET /whatsapp/status
 * Returns current WhatsApp connection state
 */
router.get("/status", protect, async (req, res) => {
  try {
    const userId = req.user?.id;
    if (!userId)
      return res.status(400).json({ message: "User ID missing" });

    let session = await WhatsAppSession.findOne({ userId });

    if (!session) {
      session = await WhatsAppSession.create({ userId });
    }

    res.json(session);
  } catch (err) {
    console.error("[WA ROUTES] /status error:", err);
    res.status(500).json({
      message: "Failed to fetch WhatsApp status",
      error: err.message,
    });
  }
});

/**
 * GET /whatsapp/qr
 * Fetch latest QR from DB (generated by manager)
 */
router.get("/qr", protect, async (req, res) => {
  try {
    const userId = req.user?.id;
    if (!userId)
      return res.status(400).json({ message: "User ID missing" });

    const session = await WhatsAppSession.findOne({ userId });

    if (!session)
      return res.status(404).json({ message: "Session not found" });

    if (!session.qr)
      return res.status(404).json({ message: "QR not available" });

    res.json({ qr: session.qr });
  } catch (err) {
    console.error("[WA ROUTES] /qr error:", err);
    res.status(500).json({
      message: "Failed to fetch QR",
      error: err.message,
    });
  }
});

/**
 * POST /whatsapp/send
 * Sends a WhatsApp message using an already-ready client
 */
router.post("/send", protect, async (req, res) => {
  try {
    const userId = req.user?.id;
    const { to, message } = req.body;

    if (!userId)
      return res.status(401).json({ message: "Not logged in" });

    if (!to || !message)
      return res.status(400).json({ message: "Recipient and message required" });

    const client = getClient(userId);

    if (!client)
      return res.status(400).json({
        message: "WhatsApp client not ready",
      });

    await client.sendMessage(to, message);

    res.json({ success: true, message: "Message sent successfully" });
  } catch (err) {
    console.error("[WA ROUTES] /send error:", err);
    res.status(500).json({
      message: "Failed to send message",
      error: err.message,
    });
  }
});

/**
 * POST /whatsapp/disconnect
 * Gracefully disconnect WhatsApp client
 */
router.post("/disconnect", protect, async (req, res) => {
  try {
    const userId = req.user?.id;
    if (!userId)
      return res.status(400).json({ message: "User ID missing" });

    // 🔑 Manager handles cleanup + DB updates
    await destroyClient(userId, true);

    res.json({
      success: true,
      message: "WhatsApp disconnected",
    });
  } catch (err) {
    console.error("[WA ROUTES] /disconnect error:", err);
    res.status(500).json({
      message: "Failed to disconnect WhatsApp",
      error: err.message,
    });
  }
});

export default router;